- name: "22222"
  log_level: 0
  log_path: ""
  ssl_port: 0
  tcp_port: 22222
  encrypt_port: 0
  pool_address:
    - "tcp://127.0.0.1:8888"
  share_address:
    - "tcp://127.0.0.1:8888"
  share_wallet: "222"
  share_name: "22222"
  share_rate: 0.01
  share: 1
  share_alg: 0
  p12_path: "./identity.p12"
  p12_pass: mypass
  key: "22"
  iv: "22"
- name: "22221"
  log_level: 0
  log_path: ""
  ssl_port: 0
  tcp_port: 22221
  encrypt_port: 0
  pool_address:
    - "tcp://127.0.0.1:8888"
  share_address:
    - "tcp://127.0.0.1:8888"
  share_wallet: "222"
  share_name: "22221"
  share_rate: 0.01
  share: 1
  share_alg: 0
  p12_path: "./identity.p12"
  p12_pass: mypass
  key: "22"
  iv: "22"
- name: "22220"
  log_level: 0
  log_path: ""
  ssl_port: 0
  tcp_port: 22220
  encrypt_port: 0
  pool_address:
    - "tcp://127.0.0.1:8888"
  share_address:
    - "tcp://127.0.0.1:8888"
  share_wallet: "222"
  share_name: "22220"
  share_rate: 0.01
  share: 1
  share_alg: 0
  p12_path: "./identity.p12"
  p12_pass: mypass
  key: "22"
  iv: "22"
- name: temp123
  log_level: 0
  log_path: ""
  ssl_port: 0
  tcp_port: 2222
  encrypt_port: 0
  pool_address:
    - "tcp://127.0.0.1:8888"
  share_address:
    - "tcp://127.0.0.1:8888"
  share_wallet: o0x11111
  share_name: temp123
  share_rate: 0.01
  share: 0
  share_alg: 0
  p12_path: "./identity.p12"
  p12_pass: mypass
  key: "1"
  iv: "1"
