[target.x86_64-unknown-linux-musl]
image = "wangyusong/x86_64-unknown-linux-musl:latest"
[target.aarch64-unknown-linux-musl]
image = "wangyusong/aarch64-unknown-linux-musl:latest"
[target.armv7-unknown-linux-gnueabihf]
image = "rustembedded/cross:armv7-unknown-linux-gnueabihf-0.1.16"